package main

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"
)

type field struct {
	Key          string
	Label        string
	Value        string
	DefaultValue string
	Secret       bool
	Page         Page
}

var fields = []field{
	{
		Key: "ARI_URL", Label: "ARI HTTP URL", DefaultValue: "http://127.0.0.1:8088", Page: PageAsterisk,
	},
	{
		Key: "ARI_USER", Label: "ARI user", DefaultValue: "bot", Page: PageAsterisk,
	},
	{
		Key: "ARI_PASSWORD", Label: "ARI password", DefaultValue: "secret", Secret: true, Page: PageAsterisk,
	},
	{
		Key: "APP_NAME", Label: "ARI app name", DefaultValue: "ivrbot", Page: PageAsterisk,
	},
	{
		Key: "CALL_ENDPOINT", Label: "PJSIP endpoint", DefaultValue: "fritzbox-endpoint", Page: PageAsterisk,
	},
	{
		Key: "SIP_USERNAME", Label: "SIP trunk username", DefaultValue: "saniTest", Page: PageAsterisk,
	},
	{
		Key: "SIP_PASSWORD", Label: "SIP trunk password", DefaultValue: "Testsani", Secret: true, Page: PageAsterisk,
	},
	{
		Key: "SIP_DOMAIN", Label: "SIP trunk domain/host", DefaultValue: "fritz.box", Page: PageAsterisk,
	},
	{
		Key: "TARGET_NUMBER", Label: "Default target number", DefaultValue: "**621", Page: PageGeneral,
	},
	{
		Key: "MODULE_WS_URL", Label: "Module WebSocket URL", DefaultValue: "ws://localhost:8080/system/moduleWS", Page: PageGeneral,
	},
	{
		Key: "MODULE_WS_KEY", Label: "Module WebSocket key", DefaultValue: "gsm-secret-key", Secret: true, Page: PageGeneral,
	},
	{
		Key: "PIPER_MODELS", Label: "Piper voice model", DefaultValue: "de_DE-thorsten-medium", Page: PageGeneral,
	},
}

func defaultFields() []field {
	result := make([]field, len(fields))
	copy(result, fields)
	values := loadEnv(envPath())
	for i := range result {
		result[i].Value = values[result[i].Key]
	}
	return result
}

func fieldsMap(items []field) map[string]string {
	values := make(map[string]string, len(items))
	for _, item := range items {
		values[item.Key] = item.Value
	}
	return values
}

func envPath() string {
	executable, err := os.Executable()

	if err == nil {
		candidate := filepath.Join(
			filepath.Dir(executable),
			"..",
			".env",
		)

		if _, err := os.Stat(candidate); err == nil {
			return candidate
		}
	}

	workingDir, err := os.Getwd()

	if err != nil {
		return ".env"
	}

	return filepath.Join(workingDir, ".env")
}

func projectDir() string {
	return filepath.Dir(envPath())
}

func loadEnv(path string) map[string]string {
	values := make(map[string]string)

	for _, item := range fields {
		values[item.Key] = item.DefaultValue
	}

	file, err := os.Open(path)

	if err != nil {
		return values
	}

	defer file.Close()

	scanner := bufio.NewScanner(file)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		if line == "" {
			continue
		}

		if strings.HasPrefix(line, "#") {
			continue
		}

		key, value, found := strings.Cut(line, "=")

		if !found {
			continue
		}

		key = strings.TrimSpace(key)

		for _, item := range fields {
			if key == item.Key {
				values[key] = value
				break
			}
		}
	}

	return values
}

func saveEnv(
	path string,
	values map[string]string,
) error {
	var output strings.Builder

	output.WriteString(
		"# Generated by SSD VOIP Setup TUI\n",
	)
	version, branch, repo := GetVersionInfo()
	if version != "dev" {
		if branch == "release" {
			output.WriteString("DOCKER_BOT_VERSION")
			output.WriteString("=")
			output.WriteString(version)
			output.WriteString("\n")
		} else {
			output.WriteString("DOCKER_BOT_VERSION")
			output.WriteString("=")
			output.WriteString(branch)
			output.WriteString("\n")
		}

		output.WriteString("DOCKER_BOT_REPO")
		output.WriteString("=")
		output.WriteString("ghcr.io/")
		output.WriteString(repo)
		output.WriteString("\n")
	}

	for _, item := range fields {
		output.WriteString(item.Key)
		output.WriteString("=")
		output.WriteString(values[item.Key])
		output.WriteString("\n")
	}

	return os.WriteFile(
		path,
		[]byte(output.String()),
		0600,
	)
}

func displayValue(value string, secret bool) string {
	if !secret || disableCensoring {
		return value
	}

	if value == "" {
		return ""
	}

	return strings.Repeat(
		"\u2022",
		min(len([]rune(value)), 24),
	)
}
