package main

import (
	"bufio"
	"encoding/base64"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

type field struct {
	key, label, defaultValue string
	secret                   bool
}

var fields = []field{
	{"ARI_URL", "ARI HTTP URL", "http://127.0.0.1:8088", false},
	{"ARI_USER", "ARI user", "bot", false},
	{"ARI_PASSWORD", "ARI password", "secret", true},
	{"APP_NAME", "ARI app name", "ivrbot", false},
	{"TARGET_NUMBER", "Default target number", "**9", false},
	{"CALL_ENDPOINT", "PJSIP endpoint", "fritzbox-endpoint", false},
	{"MODULE_WS_URL", "Module WebSocket URL", "ws://localhost:8080/system/moduleWS", false},
	{"MODULE_WS_KEY", "Module WebSocket key", "gsm-secret-key", true},
	{"PIPER_MODELS", "Piper models", "de_DE-thorsten-medium", false},
}

func envPath() string {
	if executable, err := os.Executable(); err == nil {
		candidate := filepath.Join(filepath.Dir(executable), "..", ".env")
		if _, err := os.Stat(candidate); err == nil {
			return candidate
		}
	}
	workingDir, err := os.Getwd()
	if err != nil {
		return ".env"
	}
	return filepath.Join(workingDir, ".env")
}

func projectDir() string {
	return filepath.Dir(envPath())
}

func loadEnv(path string) map[string]string {
	values := make(map[string]string, len(fields))
	for _, item := range fields {
		values[item.key] = item.defaultValue
	}
	file, err := os.Open(path)
	if err != nil {
		return values
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, found := strings.Cut(line, "=")
		if found {
			for _, item := range fields {
				if key == item.key {
					values[key] = value
				}
			}
		}
	}
	return values
}

func saveEnv(path string, values map[string]string) error {
	var output strings.Builder
	output.WriteString("# Generated by tui/setup-tui\n")
	for _, item := range fields {
		output.WriteString(item.key + "=" + values[item.key] + "\n")
	}
	return os.WriteFile(path, []byte(output.String()), 0600)
}

func displayValue(value string, secret bool) string {
	if secret && value != "" {
		return strings.Repeat("*", len(value))
	}
	return value
}

func show(values map[string]string) {
	fmt.Print("\033[H\033[2J")
	fmt.Println("SSD VOIP Module Setup")
	fmt.Println("=====================")
	for index, item := range fields {
		fmt.Printf("%d) %-24s %s\n", index+1, item.label, displayValue(values[item.key], item.secret))
	}
	fmt.Println("\nS) Save   T) Test ARI   R) Restart Docker   L) Logs   H) Shell   Q) Quit")
}

func edit(reader *bufio.Reader, values map[string]string, index int) {
	item := fields[index]
	fmt.Printf("%s [%s]: ", item.label, displayValue(values[item.key], item.secret))
	input, _ := reader.ReadString('\n')
	input = strings.TrimSpace(input)
	if input != "" {
		values[item.key] = input
	}
}

func testARI(values map[string]string) string {
	url := strings.TrimRight(values["ARI_URL"], "/") + "/ari/api-docs/resources.json"
	request, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return "ARI failed: " + err.Error()
	}
	credentials := base64.StdEncoding.EncodeToString([]byte(values["ARI_USER"] + ":" + values["ARI_PASSWORD"]))
	request.Header.Set("Authorization", "Basic "+credentials)
	client := http.Client{}
	response, err := client.Do(request)
	if err != nil {
		return "ARI failed: " + err.Error()
	}
	defer response.Body.Close()
	return fmt.Sprintf("ARI response: HTTP %d", response.StatusCode)
}

func runCommand(name string, args ...string) string {
	command := exec.Command(name, args...)
	command.Dir = projectDir()
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		return fmt.Sprintf("Command failed: %v", err)
	}
	return "Command finished"
}

func openShell() string {
	shell := os.Getenv("SHELL")
	if shell == "" {
		shell = "/bin/sh"
	}
	command := exec.Command(shell)
	command.Dir = projectDir()
	command.Stdin = os.Stdin
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		return fmt.Sprintf("Shell failed: %v", err)
	}
	return "Shell closed"
}

func main() {
	path := envPath()
	values := loadEnv(path)
	reader := bufio.NewReader(os.Stdin)
	message := "Loaded " + path

	for {
		show(values)
		fmt.Println(message)
		fmt.Print("Select field or action: ")
		command, _ := reader.ReadString('\n')
		command = strings.TrimSpace(command)
		switch strings.ToLower(command) {
		case "q", "quit":
			return
		case "s", "save":
			if err := saveEnv(path, values); err != nil {
				message = "Save failed: " + err.Error()
			} else {
				message = "Saved " + path
			}
		case "t", "test":
			message = testARI(values)
		case "r", "restart":
			message = runCommand("docker", "compose", "restart")
		case "l", "logs":
			message = runCommand("docker", "compose", "logs", "--tail=100")
		case "h", "shell":
			message = openShell()
		default:
			index, err := strconv.Atoi(command)
			if err != nil || index < 1 || index > len(fields) {
				message = "Choose a field number, S, T, or Q"
				continue
			}
			edit(reader, values, index-1)
			message = "Updated " + fields[index-1].key
		}
	}
}
